### ISSUE TITLE
Release 0.3.4 on pypi

### ISSUE THREAD

**Issue by dansbandit** [kszenes/tocPDF#2]
Can you create a new release on pypi? I'm want to update this for nixpkgs https://search.nixos.org/packages?channel=unstable&show=tocpdf&from=0&size=50&sort=relevance&type=packages&query=tocpdf

**Comment by kszenes** [comment]
Hi,
Thanks for creating the nix package. I have updated the pypi repository to the release 0.3.4.
Sorry for the delay.

**Comment by dansbandit** [comment]
It seems that I can't get the source from the latest version.
```
       last 10 log lines:
       > curl: (22) The requested URL returned error: 404
       >
       > trying https://pypi.io/packages/source/t/tocPDF/tocPDF-0.3.9.tar.gz
       >   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
       >                                  Dload  Upload   Total   Spent    Left  Speed
       > 100   122  100   122    0     0    656      0 --:--:-- --:--:-- --:--:--   659
       > 100   272  100   272    0     0    679      0 --:--:-- --:--:-- --:--:--   679
       >   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
       > curl: (22) The requested URL returned error: 404
       > error: cannot download tocPDF-0.3.9.tar.gz from any mirror
```

**Comment by kszenes** [comment]
Are you sure that you are using the correct hash in the fetchPypi function for Nix. For version 0.3.9, it should be "sha256-f3c81ad362621a7b46cff83a7f5c43cf3f45f7f87a5080b46bd9555ebe3a69ce"

**Comment by dansbandit** [comment]
This URL works for me in browser and with wget https://files.pythonhosted.org/packages/source/t/tocPDF/tocPDF-0.3.3.tar.gz

This does not https://files.pythonhosted.org/packages/source/t/tocPDF/tocPDF-0.3.9.tar.gz

Maybe it is related to this issue https://github.com/pypi/support/issues/4451?

**Comment by dansbandit** [comment]
I decided to use `fetchFromGitHub` instead.
